### ISSUE TITLE
Flag stdClass items causing problems on node save

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/flag#10]
I'm getting an error related to Flag(ings?)s being stdClass objects instead of proper Entities. I'm going to take a stab at fixing this one...
```
TypeError: Argument 1 passed to filter_entity_delete() must implement interface EntityInterface, instance of stdClass given, called in /backdrop/core/includes/module.inc on line 947 in filter_entity_delete() (line 1655 of backdrop/core/modules/filter/filter.module).
```

**Comment by jenlampton** [comment]
Well, this seems not to be a problem anymore with the latest HEAD. I'd recommend creating a new release of flag so that others don't run into this issue as well.

**Comment by ericfoy** [comment]
I dunno... I'm getting this error on my new site.
I am a newbie convert to Backdrop CMS. I love everything about Backdrop, because I am one of the disenfranchised Drupal devotees who got left behind in the wake of the whole Composer D8 death spiral... long story. Anyway, I have just launched Backdrop 1.15, and I love it so far. However, I'm getting this error when I click on a flag field. If there is any interest, I will provide whatever details you need.  —Eric

**Comment by alanmels** [comment]
Hi @ericfoy and welcome to Backdrop!

As @jenlampton says above:

> this seems not to be a problem with the latest HEAD

Have you tried the development branch of the module? If not yet, then please remove the module's directory in your setup, download https://github.com/backdrop-contrib/flag/archive/1.x-1.x.zip instead, unzip and give another try.

**Comment by ericfoy** [comment]
Thank you, alanmels, for your very quick response! I'm a total newb at GitHub; just getting the hang of this. Now I know what HEAD means. Thanks.

**Comment by ericfoy** [comment]
BTW: After following your suggestion, everything works great!

**Comment by klonos** [comment]
Sorry for coming late to the party...

Welcome to Backdrop @ericfg 👋 🎉 ...I just wore my Bug Squad member hat, and cut a new release: https://github.com/backdrop-contrib/flag/releases/tag/1.x-1.0.1 (I hope that you don't mind @jromine 😅)
