### ISSUE TITLE
HTTP error 500 when flagging content

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/flag#5]
Whenever I flag a node on forum.backdropcms.org I get a HTTP 500 error:

```
An HTTP error 500 occurred.
https://forum.backdropcms.org/flag/flag/frequently_asked_question/4?destination=node/4
```

**Comment by docwilmot** [comment]
This is because [entities are now fully classed objects](https://api.backdropcms.org/node/26881) and the `flagging` entity wasnt. So the `entity_insert()` and other `entity_*()` hook implementations in other modules (particularly `filter.module`'s `filter_entity_insert()` etc) throw an exception when Flag was passing them a STDClass "flagging" object instead of a real classed entity.

THis PR makes a "flagging" a real classed entity.

**Comment by docwilmot** [comment]
@jromine are you available to review and merge this PR please? Its holding up using Flag on Forums.

**Comment by jenlampton** [comment]
@docwilmot there should be a patches.txt file in the repo with links to any
patches that need to be applied (and their respective issues).

No patch should ever hold up using a project on a site. Here's a post on
how to do it for drupal
http://www.jenlampton.com/blog/sustainable-development-workflow-patching

**Comment by jromine** [comment]
@docwilmot I don't have an active Backdrop site to test with right now. If you want to remove me as maintainer in the README that's ok with me.

**Comment by docwilmot** [comment]
OK @jromine I'll review the patches and merge them in if you dont mind then.
Did you quit Backdrop?
